<a href="https://colab.research.google.com/github/ibonetc/IA_2024/blob/main/Heur%C3%ADstica_AlgoritmosB%C3%BAsqueda/AG_Knacksack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmo genético para el problema de la mochila

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# @title Introduzca los valores de Cantidad de productos (N) y Peso en kg (W) de la mochila
N = 10 # @param {type:"integer"}
W = 15 # @param {type:"integer"}
minprice= 1 # @param {type:"number"}
maxprice= 100 # @param {type:"number"}
NP= 50 # @param {type:"integer"}
generations= 200 # @param {type:"integer"}
mutation_probability= 0.1 # @param {type:"number"}
crossover_probability= 0.9 # @param {type:"number"}


In [ ]:
NP

50

Generar precios y pesos aleatoreamente

In [ ]:
np.random.seed(7)
weights=W*np.random.random_sample(N)
prices=(maxprice-minprice)*np.random.random_sample(N)+minprice
print(weights)
print(prices)

[ 1.14462434 11.69878188  6.57613847 10.85197767 14.66984268  8.07743806
  7.51680695  1.080767    4.0265847   7.49823751]
[68.24376962 80.57016457 38.71317218  7.52769834 29.52641433 91.04975924
 22.12515    45.76027222 93.18939595  3.46502353]


In [ ]:
ind1=np.random.randint(0,2,N)
ind1

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

## Función de validación

In [ ]:
def valid(ind):
  return 0<sum(ind*weights)<=W

## Generar primera población

In [ ]:
def generateFirstPopulation(N,NP):
  population=[]
  count=0;
  while True:
    ind=np.random.randint(0,2,N)
    if (valid(ind)):
      population.append(ind)
      count=count+1
    if count==NP:
      return population

In [ ]:
population=generateFirstPopulation(N,NP)
population

[array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0]),


## Función fitness

In [ ]:
def fitnessFunc(ind):
  return sum(ind*prices)

## Método de la ruleta

In [ ]:
sampleP=generateFirstPopulation(N,5)
print(sampleP)
f=[fitnessFunc(x) for x in sampleP]
print(f)
probability=f/sum(f)
print(probability)
accumProb=np.cumsum(probability)

[array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0]), array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0]), array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0]), array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0]), array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0])]
[183.55831556959788, 184.2391551934549, 100.71709429289776, 200.14633774689156, 183.55831556959788]
[0.21538861 0.21618752 0.11818214 0.23485311 0.21538861]


In [ ]:
df=pd.DataFrame(list(zip(sampleP,f,probability,accumProb)),columns=['Cromosoma','Fitness','Probabilidad','Prob_Acumulada'])
df

Cromosoma     Fitness  Probabilidad  Prob_Acumulada
0  [1, 0, 0, 0, 0, 0, 1, 0, 1, 0]  183.558316      0.215389        0.215389
1  [0, 0, 0, 0, 0, 1, 0, 0, 1, 0]  184.239155      0.216188        0.431576
2  [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]  100.717094      0.118182        0.549758
3  [1, 0, 1, 0, 0, 0, 0, 0, 1, 0]  200.146338      0.234853        0.784611
4  [1, 0, 0, 0, 0, 0, 1, 0, 1, 0]  183.558316      0.215389        1.000000

In [ ]:
import plotly.graph_objects as go
fig=go.Figure(data=[go.Pie(labels=np.arange(5), values=f)])
fig.show()

In [ ]:
def roulette(population):
  f=[fitnessFunc(x) for x in population]
  probability=f/sum(f)
  accumProb=np.cumsum(probability)
  return accumProb

## Operador de selección

In [ ]:
nr=np.random.uniform()
nr

0.6754061724686846

In [ ]:
population

[array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0]),


In [ ]:
def selection(population, accumProb):
  nr=np.random.uniform()
  for i, p in enumerate(accumProb):
    if nr<p:
      return (i, population[i])

In [ ]:
selection(population, accumProb)

(4, array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0]))

## Operador de Mutación

In [ ]:
def mutate(ind):
  mp=np.random.randint(0,len(ind))
  child=np.copy(ind)
  child[mp]=not child[mp]
  return child

In [ ]:
population[1]

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
mutate(population[1])

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0])

## Operador de Cruce

In [ ]:
def crossover(ind1, ind2):
  cp=np.random.randint(1,len(ind1))
  child1=np.concatenate((ind1[0:cp],ind2[cp:len(ind2)]))
  child2=np.concatenate((ind2[0:cp],ind1[cp:len(ind1)]))
  return child1,child2

In [ ]:
ind1=population[1]
ind2=population[3]
print(ind1)
print(ind2)

[0 0 1 0 0 1 0 0 0 0]
[0 0 0 0 0 0 1 1 1 0]


In [ ]:
crossover(ind1, ind2)

(array([0, 0, 1, 0, 0, 0, 1, 1, 1, 0]), array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0]))

## Método de algoritmo genético

In [ ]:
  ff=[fitnessFunc(i) for i in population]
  ff

[129.76293142594704,
 129.76293142594704,
 136.81003146419238,
 161.0748181735754,
 159.29352886021485,
 136.81003146419238,
 90.36891962038474,
 161.0748181735754,
 194.5742064102569,
 142.41469169664822,
 245.90660996684218,
 60.83832218611694,
 164.8981890926707,
 106.95694179767841,
 177.6628403508691,
 200.14633774689156,
 161.0748181735754,
 205.05380108016547,
 136.12919184033538,
 131.90256813091844,
 117.46906536340819,
 194.5742064102569,
 91.04975924424176,
 67.88542222436226,
 138.94966816916377,
 29.52641433149136,
 121.53174017960833,
 177.6628403508691,
 159.29352886021485,
 91.04975924424176,
 252.482924809428,
 194.5742064102569,
 148.81393419030627,
 207.1934377851369,
 159.29352886021485,
 117.46906536340819,
 29.52641433149136,
 152.71721401762903,
 252.482924809428,
 205.05380108016547,
 60.83832218611694,
 84.47344440165594,
 49.225295747435084,
 142.41469169664822,
 96.6544194766976,
 3.4650235274844534,
 298.2431970293786,
 96.6544194766976,
 3.4650235274844534,

In [ ]:
population[np.argmax(ff)]

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [ ]:
sorted(population,key=fitnessFunc, reverse=True)

[array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([1, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1]),


In [ ]:
def geneticAlgorithm(sizeIndividual, sizePopulation,generations, mutation_probability,crossover_probatility):
  population=generateFirstPopulation(sizeIndividual, sizePopulation)
  accumulatedP=roulette(population)
  ff=[fitnessFunc(i) for i in population]
  bestIndividual=[population[np.argmax(ff)]] # Lista de los mejores
  for i in range(generations):
    newPopulation=[]
    cont=0
    while True:
      # Cruce
      ind1=selection(population, accumulatedP)[1]
      ind2=selection(population, accumulatedP)[1]
      crossProb=np.random.uniform()
      if crossProb<=crossover_probatility:
        child1,child2=crossover(ind1, ind2)
        if valid(child1):
          newPopulation.append(child1)
        if valid(child2):
          newPopulation.append(child2)
      else:
        newPopulation.append(ind1)
        newPopulation.append(ind2)
      # Mutación
      ind1=selection(population, accumulatedP)[1]
      mProb=np.random.uniform()
      if mProb <=mutation_probability:
        child=mutate(ind1)
        if valid(child):
          newPopulation.append(child)
      else:
        newPopulation.append(ind1)
      if len(newPopulation)>=sizePopulation:
        newPopulation=newPopulation[0:sizePopulation]
        break
    accumulatedP=roulette(newPopulation)
    ff=[fitnessFunc(i) for i in newPopulation]
    bestIndividual.append(newPopulation[np.argmax(ff)])
    population=newPopulation
  sortedBest=sorted(bestIndividual,key=fitnessFunc, reverse=True)
  return bestIndividual, sortedBest[0]

In [ ]:
np.random.seed()
bestList, bestInd=geneticAlgorithm(N,NP, generations,mutation_probability, crossover_probability)
bestInd

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [ ]:
sum(bestInd*prices)

298.2431970293786

In [ ]:
import plotly.express as px

In [ ]:
print(sum(bestInd*prices))
iteration=np.arange(0,len(bestList))
fitnessValue=[fitnessFunc(x) for x in bestList]
df=pd.DataFrame(list(zip(iteration,fitnessValue)),columns=['Iteración','Fitness'])
fig=px.line(df,x='Iteración',y='Fitness')
fig.show()

298.2431970293786
